services:
  mysql-db:
    restart: always
    image: mysql:8.0
    container_name: mysql_database
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
  eureka:
    restart: always
    build:
      context: ./eureka
      dockerfile: Dockerfile
    container_name: eureka
    ports:
      - "8761:8761"
    depends_on:
      mysql-db:
        condition: service_started
  config-server:
    restart: always
    build:
      context: ./config-server
      dockerfile: Dockerfile
    container_name: config-server
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka/
      CONFIG_SEARCH_LOCATIONS: file:/config-microservicios
    ports:
      - "8888:8888"
    volumes:
      - ./config-microservicios:/config-microservicios
    depends_on:
      mysql-db:
        condition: service_started
      eureka:
        condition: service_started
  cliente:
    restart: always
    build:
      context: ./cliente
      dockerfile: Dockerfile
    container_name: clientes
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka/
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8888
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/bd_clientes
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      mysql-db:
        condition: service_started
      eureka:
        condition: service_started
      config-server:
        condition: service_started
  cocinero:
    restart: always
    build:
      context: ./cocinero
      dockerfile: Dockerfile
    container_name: cocineros
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka/
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8888
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/bd_cocineros
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      mysql-db:
        condition: service_started
      eureka:
        condition: service_started
      config-server:
        condition: service_started
  pedido:
    restart: always
    build:
      context: ./pedido
      dockerfile: Dockerfile
    container_name: pedidos
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka/
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8888
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/bd_pedidos
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      mysql-db:
        condition: service_started
      eureka:
        condition: service_started
      config-server:
        condition: service_started
  producto:
    restart: always
    build:
      context: ./producto
      dockerfile: Dockerfile
    container_name: productos
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka/
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8888
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/bd_productos
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      mysql-db:
        condition: service_started
      eureka:
        condition: service_started
      config-server:
        condition: service_started
  repartidores:
    restart: always
    build:
      context: ./repartidores
      dockerfile: Dockerfile
    container_name: repartidores
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka/
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8888
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/bd_repartidores
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      mysql-db:
        condition: service_started
      eureka:
        condition: service_started
      config-server:
        condition: service_started
  sucursales:
    restart: always
    build:
      context: ./sucursales
      dockerfile: Dockerfile
    container_name: sucursales
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka/
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8888
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/bd_sucursales
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      mysql-db:
        condition: service_started
      eureka:
        condition: service_started
      config-server:
        condition: service_started
  vehiculos:
    restart: always
    build:
      context: ./vehiculos
      dockerfile: Dockerfile
    container_name: vehiculos
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka/
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8888
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/bd_vehiculos
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      mysql-db:
        condition: service_started
      eureka:
        condition: service_started
      config-server:
        condition: service_started
  vendedor:
    restart: always
    build:
      context: ./vendedor
      dockerfile: Dockerfile
    container_name: vendedores
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka/
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8888
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/bd_vendedores
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      mysql-db:
        condition: service_started
      eureka:
        condition: service_started
      config-server:
        condition: service_started
  api-gateway:
    restart: always
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "9090:9090"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka/
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8888
    depends_on:
      - eureka
      - config-server
      - cliente
      - cocinero
      - pedido
      - producto
      - repartidores
      - sucursales
      - vehiculos
      - vendedor
      - mysql-db
volumes:
  mysql_data:


