spring.application.name=api-gateway

# Puerto del Gateway
server.port=8080

# Configuracion de EUREKA
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

# Ruta para el microservicio de VEHICULOS
spring.cloud.gateway.server.webflux.routes[0].id=vehiculos
spring.cloud.gateway.server.webflux.routes[0].uri=lb://vehiculos
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/v1/vehiculos/**
