spring.application.name=api-gateway

# Puerto del Gateway
server.port=8080

# Configuracion de EUREKA
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

# Ruta para el microservicio de VEHICULOS
spring.cloud.gateway.server.webflux.routes[0].id=vehiculos
spring.cloud.gateway.server.webflux.routes[0].uri=lb://vehiculos
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/v1/vehiculos/**

# Ruta para el microservicio de SUCURSALES
spring.cloud.gateway.server.webflux.routes[1].id=sucursales
spring.cloud.gateway.server.webflux.routes[1].uri=lb://sucursales
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/v1/sucursales/**

# Ruta para el microservicio de REPARTIDORES
spring.cloud.gateway.server.webflux.routes[2].id=repartidores
spring.cloud.gateway.server.webflux.routes[2].uri=lb://repartidores
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/v1/repartidores/**

# Ruta para el microservicio de Producto
spring.cloud.gateway.server.webflux.routes[2].id=producto
spring.cloud.gateway.server.webflux.routes[2].uri=lb://producto
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/v1/producto/**
