CREATE DATABASE IF NOT EXISTS bd_clientes;
CREATE DATABASE IF NOT EXISTS bd_cocineros;
CREATE DATABASE IF NOT EXISTS bd_pedidos;
CREATE DATABASE IF NOT EXISTS bd_productos;
CREATE DATABASE IF NOT EXISTS bd_repartidores;
CREATE DATABASE IF NOT EXISTS bd_sucursales;
CREATE DATABASE IF NOT EXISTS bd_vehiculos;
CREATE DATABASE IF NOT EXISTS bd_vendedores;