server.port=8080
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

# Ruta para el microservicio de VEHICULOS
spring.cloud.gateway.server.webflux.routes[0].id=vehiculos
spring.cloud.gateway.server.webflux.routes[0].uri=lb://vehiculos
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/v1/vehiculos/**

# Ruta para el microservicio de SUCURSALES
spring.cloud.gateway.server.webflux.routes[1].id=sucursales
spring.cloud.gateway.server.webflux.routes[1].uri=lb://sucursales
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/v1/sucursales/**

# Ruta para el microservicio de REPARTIDORES
spring.cloud.gateway.server.webflux.routes[2].id=repartidores
spring.cloud.gateway.server.webflux.routes[2].uri=lb://repartidores
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/v1/repartidores/**

# Ruta para el microservicio de Cliente
spring.cloud.gateway.server.webflux.routes[3].id=clientes
spring.cloud.gateway.server.webflux.routes[3].uri=lb://clientes
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/api/v1/clientes/**

# Ruta para el microservicio de Cocinero
spring.cloud.gateway.server.webflux.routes[4].id=cocineros
spring.cloud.gateway.server.webflux.routes[4].uri=lb://cocineros
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/api/v1/cocineros/**

# Ruta para el microservicio de Pedido
spring.cloud.gateway.server.webflux.routes[5].id=pedidos
spring.cloud.gateway.server.webflux.routes[5].uri=lb://pedidos
spring.cloud.gateway.server.webflux.routes[5].predicates[0]=Path=/api/v1/pedidos/**

# Ruta para el microservicio de Producto
spring.cloud.gateway.server.webflux.routes[6].id=productos
spring.cloud.gateway.server.webflux.routes[6].uri=lb://productos
spring.cloud.gateway.server.webflux.routes[6].predicates[0]=Path=/api/v1/productos/**

# Ruta para el microservicio de Vendedor
spring.cloud.gateway.server.webflux.routes[7].id=vendedores
spring.cloud.gateway.server.webflux.routes[7].uri=lb://vendedores
spring.cloud.gateway.server.webflux.routes[7].predicates[0]=Path=/api/v1/vendedores/**