server:
  port: 8080

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: vehiculos
              uri: lb://vehiculos
              predicates:
                - Path=/api/v1/vehiculos/**, /v3/api-docs/vehiculos
              filters:
                - RewritePath=/v3/api-docs/vehiculos, /v3/api-docs

            - id: sucursales
              uri: lb://sucursales
              predicates:
                - Path=/api/v1/sucursales/**, /v3/api-docs/sucursales
              filters:
                - RewritePath=/v3/api-docs/sucursales, /v3/api-docs

            - id: repartidores
              uri: lb://repartidores
              predicates:
                - Path=/api/v1/repartidores/**, /v3/api-docs/repartidores
              filters:
                - RewritePath=/v3/api-docs/repartidores, /v3/api-docs

            - id: clientes
              uri: lb://clientes
              predicates:
                - Path=/api/v1/clientes/**, /v3/api-docs/clientes
              filters:
                - RewritePath=/v3/api-docs/clientes, /v3/api-docs

            - id: cocineros
              uri: lb://cocineros
              predicates:
                - Path=/api/v1/cocineros/**, /v3/api-docs/cocineros
              filters:
                - RewritePath=/v3/api-docs/cocineros, /v3/api-docs

            - id: pedidos
              uri: lb://pedidos
              predicates:
                - Path=/api/v1/pedidos/**, /v3/api-docs/pedidos
              filters:
                - RewritePath=/v3/api-docs/pedidos, /v3/api-docs

            - id: productos
              uri: lb://productos
              predicates:
                - Path=/api/v1/productos/**, /v3/api-docs/productos
              filters:
                - RewritePath=/v3/api-docs/productos, /v3/api-docs

            - id: vendedores
              uri: lb://vendedores
              predicates:
                - Path=/api/v1/vendedores/**, /v3/api-docs/vendedores
              filters:
                - RewritePath=/v3/api-docs/vendedores, /v3/api-docs

springdoc:
  swagger-ui:
    defaultModelsExpandDepth: -1
    path: /swagger-ui.html
    urls:
      - name: vehiculos
        url: v3/api-docs/vehiculos
      - name: sucursales
        url: v3/api-docs/sucursales
      - name: repartidores
        url: v3/api-docs/repartidores
      - name: clientes
        url: v3/api-docs/clientes
      - name: cocineros
        url: v3/api-docs/cocineros
      - name: pedidos
        url: v3/api-docs/pedidos
      - name: productos
        url: v3/api-docs/productos
      - name: vendedores
        url: v3/api-docs/vendedores

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
